#server:  
 # port: 8010 #${PORT:0}
  #error:    
    #include-message: always

#EUREKA CUSTOMER
eureka:
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-server:8761/eureka

#DB MONGO
spring:
  data:
    mongodb:
      host: localhost
      #host: dbmongo
      port: 27017
      database: dbprofile 
